# -*- coding: utf-8 -*-
"""Sujet Projet Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dPJs_d-NOL78rDxFGm1XP00iQf-g8imS

# **Agent IA Conversationnel pour le programme Force-N**
"""


import os
import chromadb
from dotenv import load_dotenv
from mistralai.client import Mistral
import shutil # Import shutil for directory removal
# Bibliothèque permettant d'envoyer des requêtes HTTP
import requests
# Permet d'analyser le code HTML
from bs4 import BeautifulSoup
# Permet de créer l'empreinte SHA-256 de la page
import hashlib
# Permet de faire une pause entre deux vérifications
import time, datetime
# Bibliothèque permettant d'envoyer des e-mails
import smtplib
# Permet de construire correctement le contenu de l'e-mail
from email.mime.text import MIMEText
# Permet de construire l'en-tête de l'e-mail
from email.mime.multipart import MIMEMultipart
from numpy import asarray_chkfinite

historiques=[]
historiques_tempo=[]


load_dotenv()

#Créer le client Mistral
client = Mistral(
    api_key=os.environ["Mistral_api_key"]
)

# Define the path for ChromaDB - Changed to /tmp/chroma_db
chroma_db_path = "chroma_db"

# Ensure the directory for ChromaDB is clean before initialization
# This helps in avoiding 'no such table' errors if the database was corrupted
if os.path.exists(chroma_db_path):
    shutil.rmtree(chroma_db_path) # Remove the directory and its contents
    print(f"Removed existing ChromaDB directory: {chroma_db_path}")

# Ensure the directory exists (will recreate if removed)
os.makedirs(chroma_db_path, exist_ok=True)

#Créer ChromaDB
chroma = chromadb.PersistentClient(path=chroma_db_path)

#Créer une collection
collection = chroma.get_or_create_collection("FORCE-N")



"""# **Découper le document (Chunking)**"""
CHUNK_SIZE    = 300   # Taille de chaque extrait en caracteres
CHUNK_OVERLAP = 100   # Chevauchement entre extraits consecutifs
TOP_K         = 4     # Nombre d'extraits recuperes par question
BATCH_SIZE    = 48    # Petit batch pour eviter les crashes RAM sur Colab


########   Decoupage du document en chucks
def charger_et_decouper(texte, taille=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    import re

    if texte is None:
        raise ValueError(f"Impossible de lire le fichier")

    # Nettoyage
    texte = re.sub(r'\n{3,}', '\n\n', texte).strip()
    print(f"Taille du texte : {len(texte)} caracteres")

    # Securite anti-boucle infinie
    if overlap >= taille:
        raise ValueError(f"overlap ({overlap}) doit etre inferieur a taille ({taille})")

    # Decoupage avec chevauchement
    chunks, debut, idx = [], 0, 0
    while debut < len(texte):
        fin = min(debut + taille, len(texte))
        if fin < len(texte):
            coupe = texte.rfind('.', debut, fin)
            if coupe > debut:
                fin = coupe + 1
        chunk = texte[debut:fin].strip()
        if chunk:
            chunks.append({"id": f"chunk_{idx:04d}", "texte": chunk})
            idx += 1
        nouveau_debut = fin - overlap
        if nouveau_debut <= debut:   # securite absolue anti-boucle infinie
            nouveau_debut = debut + 1
        debut = nouveau_debut

    return chunks


"""# **Créer un embedding**"""
def embedding(text):

    response = client.embeddings.create(
        model="mistral-embed",
        inputs=[text] # Changed 'inputs=text' to 'inputs=[text]'
    )

    return response.data[0].embedding

"""# **Ajouter chaque chunk dans ChromaDB**"""

#chemin du document qui contient les fichier
folder = "documents"

#parcourir les fichier
for filename in os.listdir(folder):
  try:
    #chemin du fichier
    path = os.path.join(folder, filename)

    #lecture du fichier
    with open(path, encoding="utf8") as f:
      # Chargement avec fallback encodage
      texte = None
      for encodage in ["utf-8", "latin-1", "cp1252"]:
          try:
              with open(path, "r", encoding=encodage) as f:
                  texte = f.read()
              print(f"Fichier lu avec encodage : {encodage}")
              break
          except UnicodeDecodeError:
              continue

    #decoupage du documents en chunks
    chunks = charger_et_decouper(texte)
    print(f"Document {filename} charge : {len(chunks)} chunks")
  except:
    pass

  #Ajouter chaque chunk dans ChromaDB
  for index, chunk in enumerate(chunks):

    try:
      emb = embedding(chunk) # Changed from embedding(chunk) to embedding(chunk['texte'])
      collection.add(

        ids=[f"{filename}_{index}"],

        documents=[chunk], # Also changed from chunk to chunk['texte'] for documents

        embeddings=[emb],

        metadatas=[

            {
                "source": filename,
                "chunk": index
            }

        ]

      )
    except:
      pass

"""# **fonction pour interoger chromadb avec la question de l'utilisateur**"""

#fonction pour interoger chromadb avec la question de l'utilisateur
def recherche(question):
    #transformer la question en vecteur
    question_embedding = embedding(question)

    #interrogeons chromadb
    result = collection.query(

        query_embeddings=[
            question_embedding
        ],

        n_results=3,
        include=["documents", "distances"]
    )

    return result["documents"][0]



"""# **FONCTION D'ENVOI DE L'EMAIL**"""

# ==============================
# CONFIGURATION DE L'EMAIL
# ==============================

def envoyer_email(question_user,emailD):
    # Adresse du site à surveiller
    URL = "https://force-n.sn/actualites"
    # Adresse Gmail qui va envoyer l'e-mail
    EMAIL_EXPEDITEUR = os.environ["mon_email"]

    # Mot de passe d'application Gmail
    EMAIL_PASSWORD = os.environ["SMTP_password_app_gmail"] #""      

    # Adresse qui recevra l'alerte
    if emailD == "":
      EMAIL_DESTINATAIRE = os.environ["dest_email"]
    else:
      EMAIL_DESTINATAIRE = emailD   

    #gestion de la question
    if question_user == "":
      question_user = "aucune qestion pauser"

    # Création du message
    message = MIMEMultipart()

    # Adresse de l'expéditeur
    message["From"] = EMAIL_EXPEDITEUR

    # Adresse du destinataire
    message["To"] = EMAIL_DESTINATAIRE

    # Objet de l'e-mail
    message["Subject"] = "🚨 Nouveau utilisateur sur chat bot Force-N"

    #récupérons la date
    maintenant = datetime.datetime.now()
    aujourdui = datetime.datetime.today()
    heure = maintenant.hour
    minute = maintenant.minute
    seconde = maintenant.second

    #récupérer le lieu
    data = requests.get("https://ipinfo.io/json").json()

    # Contenu du message
    texte = f"""
    Bonjour,
    Le programme de surveillance a détecté un nouveau utilisateur.

    Un utilisateur viens d'utiliser chat bot Force-N le \n

    date : {aujourdui.strftime("%d/%m/%Y")}\n
    heure : {heure}h{minute}mn{seconde}s \n
    ville : {data.get("city")} \n
    pays : {data.get("country")} \n
    coordonnées : {data.get("loc")} \n

    il a pausé les questions suivantes :\n{question_user}

    Cordialement,\n
    Système automatique de surveillance\n
    """

    # Ajout du texte dans l'e-mail
    message.attach(MIMEText(texte, "plain", "utf-8"))

    try:

        # Connexion au serveur SMTP de Gmail
        serveur = smtplib.SMTP("smtp.gmail.com", 587)

        # Active le chiffrement TLS
        serveur.starttls()

        # Connexion au compte Gmail
        serveur.login(
            EMAIL_EXPEDITEUR,
            EMAIL_PASSWORD
        )

        # Envoi de l'e-mail
        serveur.sendmail(
            EMAIL_EXPEDITEUR,
            EMAIL_DESTINATAIRE,
            message.as_string()
        )

        # Fermeture de la connexion
        serveur.quit()

        return "📧 E-mail envoyé avec succès !"

    except Exception as erreur:

        # Affiche l'erreur en cas de problème
        return f"❌ Erreur lors de l'envoi :{erreur}"


"""# **Netoyer TEXTE retouner par mistral**"""

import re
def nettoyer_reponse(texte):

    # Supprimer les titres Markdown : # ## ###
    texte = re.sub(
        r'^\s*#+\s*',
        '',
        texte,
        flags=re.MULTILINE
    )

    # Supprimer les astérisques
    texte = texte.replace("*", "")

    # Supprimer les underscores utilisés pour l'italique
    texte = texte.replace("_", "")

    # Supprimer les backticks
    texte = texte.replace("`", "")

    # Supprimer les chevrons de citation Markdown
    texte = re.sub(
        r'^\s*>\s?',
        '',
        texte,
        flags=re.MULTILINE
    )

    # Nettoyer les espaces multiples
    texte = re.sub(
        r' {2,}',
        ' ',
        texte
    )

    return texte.strip()

"""# **Fontion qui fournit les infos a mistral pour une réponse definitif de mistral**"""

def ask_mistral(question,emailDest):
    # ------------------------------------------------------
    # ÉTAPE 1 : afficher l'indicateur de réflexion
    # ------------------------------------------------------

    # parametre pour afficher l'historique
    historiques_tempo.append(f"👤 Vous : {question} \n ")
    texte_historique = reversed(historiques_tempo)
    texte_historique = "\n".join(texte_historique)
    #return stream_response.choices[0].message.content

    #affichage patienter
    # Modified to return 4 values: output, empty string for question, empty string for email, history
    yield "🤖 Force-N réfléchit ⏳ patiente quelques secondes...","","",texte_historique

    #envoi du mail d'alert
    rep_mail = envoyer_email(texte_historique,emailDest)


    # ------------------------------------------------------
    # ÉTAPE 2 : lecture du fichier prompt system
    # ------------------------------------------------------
    #prompt system

    SYSTEME=""
    while SYSTEME=="":
      with open("prompt_system.txt", "r", encoding=encodage) as f:
          SYSTEME = f.read()
          if SYSTEME:
           continue
          else:
            print("prompt system absent")

    # ------------------------------------------------------
    # ÉTAPE 3 : interroger chromadb avec la question de l'utilisateur
    # ------------------------------------------------------

    documents = recherche(question)
    context = "\n\n".join(documents)
    promt = f"""
    context : {context}
    question : {question}
    """

    #ajouter la question de l'utilisateur et les chunk provenant de chromadb a l'historiques
    historiques.append({"role": "system", "content": SYSTEME})
    historiques.append({"role":"user","content":promt })

    # ------------------------------------------------------
    # ÉTAPE 4 : interrogation de mistral
    # ------------------------------------------------------

    stream_response = client.chat.stream(
      model="mistral-large-latest",
      messages=historiques,
      stream=True,
      temperature=0.8
    )

    # ------------------------------------------------------
    # ÉTAPE 5 : envoi du résultat de mistral
    # ------------------------------------------------------

    res =""
    for event in stream_response:
        if event.data and event.data.choices:
            res += event.data.choices[0].delta.content
            # Modified to return 4 values: output, empty string for question, empty string for email, history
            yield f"\n🤖 Force-N :\n{res}   ✍️", "","",texte_historique #if i < len(historiques)

    res = nettoyer_reponse(res)
    historiques.append({"role":"assistant","content":res})


#EFFACER HISTORIQUES
def efface_historiques():
    historiques_tempo.clear()
    return ""



"""# **Interface avec Gradio**"""

# CSS personnalisé
css = """
.tout {
    background-color: #989ca3;
}

.titre {
    text-align : justify;
    font-size:17px;
}

#logo {
    
}

.corps {
    background:#f5f5f5;
    padding:15px;
    border-radius:10px;
    border-left:5px solid #0d6efd;
}

.resultat {
    background-color: #E8F5E9;
    border: 1px solid #4CAF50;
    border-radius: 8px;
    padding: 10px;
}
"""


import gradio as gr
#utilisation de gradio pour l'interface graphique avec Blocks
with gr.Blocks(css=css, title="FORCE-N!!!!!", elem_classes="tout") as demo1: # Title for browser tab
    #with gr.Row(): # New row for the logo
      #gr.Markdown("<center><h1>Interogez vous sur le code du travail.</h1></center>") # Visual title inside the app

    with gr.Column(scale=1):
        with gr.Row(scale=1):
            gr.Image(value="C:/Users/HP/Documents/Python/LLM/Exam de projet Force-N chatBot/logo.png", show_label=False, container=False, elem_id="logo", width=150, height=100)
        

    with gr.Row():
        with gr.Column(scale=1):
            Text_his = gr.Textbox(lines=15, label="Historiques")

            bt_efface_his = gr.Button("Effacer historiques", variant="primary", size="lg")
            bt_efface_his.click(fn=efface_historiques, inputs=None, outputs=Text_his)

        with gr.Column(scale=2): # Example of layout with Rows and Columns
            text_output = gr.Textbox(
            lines=15,
            label="Voici la réponse à votre question",
            )

            # Assign individual textboxes to variables
            question_textbox = gr.Textbox(
                lines=2,
                autofocus=True,
                label="Entrez votre question",
                placeholder="Entrez votre question ici..."
            )
            email_textbox = gr.Textbox(
                lines=1,
                label="Entrez votre email pour recevoir l'historique de la discution",
                placeholder="Entrez votre email ici..."
            )

            # Group them for inputs to the function
            text_input = [question_textbox, email_textbox]


    with gr.Row():
        with gr.Column(scale=1):
            submit_button = gr.Button("Envoyer", variant="secondary", size="lg")
            # Correct the outputs to refer to individual components
            submit_button.click(ask_mistral, inputs=text_input,show_progress="hidden", outputs=[text_output, question_textbox, email_textbox, Text_his])


demo1.launch(theme=gr.themes.Ember(primary_hue="blue"))

